package com.example.zerohaus.Util

import androidx.compose.runtime.compositionLocalOf

data class AppCadenas(
    // Common
    val volver: String,
    val guardar: String,
    val guardarCambios: String,
    val cancelar: String,
    val cerrar: String,
    val subir: String,
    val cerrarSesion: String,
    val mostrar: String,
    val ocultar: String,
    val emailPlaceholder: String,
    val emailError: String,
    val contrasena: String,
    val contrasenaPlaceholder: String,
    val contrasenaError: String,

    // Auth - Login
    val loginTitulo: String,
    val loginSlogan: String,
    val loginOlvidaste: String,
    val loginBoton: String,
    val loginCrearCuenta: String,

    // Auth - Registro
    val registroTitulo: String,
    val registroSubtitulo: String,
    val registroNombre: String,
    val registroNombrePlaceholder: String,
    val registroNombreError: String,
    val registroTipoUsuario: String,
    val registroContrasenaNumeroLetra: String,
    val registroConfirmar: String,
    val registroConfirmarPlaceholder: String,
    val registroContrasenasNoCoinciden: String,
    val registroBoton: String,
    val registroYaTieneCuenta: String,
    val registroIniciarSesion: String,
    val tipoPropietario: String,
    val tipoTecnico: String,

    // Auth - Recuperar
    val recuperarTitulo: String,
    val recuperarSubtitulo: String,
    val recuperarBoton: String,
    val recuperarExito: String,
    val recuperarVolver: String,

    // Splash
    val splashSlogan: String,

    // Tabs
    val tabInicio: String,
    val tabMensajes: String,
    val tabExplorar: String,
    val tabMas: String,

    // Explorar
    val explorarTitulo: String,
    val explorarSubtitulo: String,
    val explorarBuscarTecnicos: String,
    val explorarBuscarTecnicosSub: String,
    val explorarMapaTecnicos: String,
    val explorarMapaTecnicosSub: String,
    val explorarRankings: String,
    val explorarRankingsSub: String,
    val explorarGraficas: String,
    val explorarGraficasSub: String,
    val explorarHistorial: String,
    val explorarHistorialSub: String,

    // Más
    val masTitulo: String,
    val masSubtitulo: String,
    val masPerfil: String,
    val masPerfilSub: String,
    val masViviendas: String,
    val masViviendasSub: String,
    val masPresupuestos: String,
    val masPresupuestosSub: String,
    val masProyectos: String,
    val masProyectosSub: String,
    val masAjustes: String,
    val masAjustesSub: String,
    val masSobreApp: String,
    val masSobreAppSub: String,

    // Panel
    val panelSaludo: String,
    val panelSubtitulo: String,
    val panelVivienda: String,
    val panelSinVivienda: String,
    val panelConsumo: String,
    val panelEmisiones: String,
    val panelCoste: String,
    val panelSinDatos: String,
    val panelVerInforme: String,
    val panelCrearPreestudio: String,
    val panelAccionesRapidas: String,
    val panelNuevoPreestudio: String,
    val panelNuevoPreestudioSub: String,
    val panelMisViviendasSub: String,
    val panelBuscarTecnicosSub: String,
    val panelMapaTecnicosSub: String,
    val panelMensajes: String,
    val panelMensajesSub: String,
    val panelMisProyectosSub: String,
    val panelRankingsSub: String,
    val panelPresupuestosSub: String,
    val panelHistorialInformesSub: String,
    val panelGraficasSub: String,
    val panelNotificaciones: String,
    val panelSinNotificaciones: String,
    val panelMarcarLeidas: String,
    val panelSubirCertificado: String,
    val panelNombreLabel: String,
    val panelTipoLabel: String,
    val panelSeleccionarArchivo: String,
    val panelArchivoSeleccionado: String,
    val panelCertificadoSubido: String,

    // Ajustes
    val ajustesTitulo: String,
    val ajustesSubtitulo: String,
    val ajustesNotificaciones: String,
    val ajustesPush: String,
    val ajustesPushSub: String,
    val ajustesEmailSub: String,
    val ajustesSonido: String,
    val ajustesSonidoSub: String,
    val ajustesApariencia: String,
    val ajustesTema: String,
    val ajustesTemaClaro: String,
    val ajustesTemaDark: String,
    val ajustesTemaSystem: String,
    val ajustesPreferencias: String,
    val ajustesIdioma: String,
    val ajustesUnidadEnergia: String,
    val ajustesMoneda: String,
    val ajustesGuardar: String,
    val ajustesGuardados: String,

    // Sobre App
    val sobreTitulo: String,
    val sobreVersion: String,
    val sobreQueEs: String,
    val sobreDescripcion: String,
    val sobreFuncionalidades: String,
    val sobreCopyright: String,
    val sobreFuncPreestudios: String,
    val sobreFuncViviendas: String,
    val sobreFuncBusqueda: String,
    val sobreFuncChat: String,
    val sobreFuncPresupuestos: String,
    val sobreFuncGraficas: String,
    val sobreFuncValoraciones: String,

    // Perfil
    val perfilTitulo: String,
    val perfilSubtitulo: String,
    val perfilDatosPersonales: String,
    val perfilNombrePlaceholder: String,
    val perfilEmailLabel: String,
    val perfilTipoUsuarioLabel: String,
    val perfilFotoTexto: String,
    val perfilGuardar: String,
    val perfilGuardado: String,
    val perfilTecnicoTitulo: String,
    val perfilEspecialidades: String,
    val perfilEspecialidadesPlaceholder: String,
    val perfilDescripcionProf: String,
    val perfilDescripcionPlaceholder: String,
    val perfilTelefonoPlaceholder: String,
    val perfilEmailContacto: String,
    val perfilEmailContactoPlaceholder: String,
    val perfilCuenta: String,
)

val LocalCadenas = compositionLocalOf<AppCadenas> { error("LocalCadenas not provided") }
